FROM        gori-front-base
MAINTAINER  gsh2448@gmail.com

RUN         pip3 install -r requirements.txt
RUN         pip3 install uwsgi

RUN         apt-get -y install curl && \
            curl -sL https://deb.nodesource.com/setup_7.x | bash - && \
            apt-get -y install nodejs
