FROM        gori-front-base
MAINTAINER  gsh2448@gmail.com

RUN         apt-get -y install curl && \
            curl -sL https://deb.nodesource.com/setup_7.x | bash - && \
            apt-get -y install nodejs

