FROM        ubuntu:16.04
MAINTAINER  gsh2448@gmail.com

RUN         apt-get -y update
RUN         apt-get -y install python3
RUN         apt-get -y install python3-pip
RUN         apt-get -y install nginx
RUN         apt-get -y install supervisor

COPY        . srv/app
WORKDIR     /srv/app



