# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goriuser',
            name='cellphone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='goriuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
