# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goriuser',
            name='name',
            field=models.CharField(error_messages={'invalid': 'your custom error message'}, max_length=30),
        ),
    ]
