# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170411_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goriuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='member/profile_image/default_profile.png', upload_to='member/profile_image'),
        ),
    ]
