# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import storages.backends.overwrite


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170405_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goriuser',
            name='profile_image',
            field=models.ImageField(blank=True, storage=storages.backends.overwrite.OverwriteStorage(), upload_to='member/profile_image'),
        ),
    ]
