# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20170406_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goriuser',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='member/profile_image'),
        ),
    ]
