# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20170406_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goriuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
