# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_auto_20170328_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goriclass',
            name='class_type',
            field=models.IntegerField(choices=[(0, '1:1'), (1, '그룹 수업'), (2, '원데이 수업')], default='1'),
        ),
    ]
