# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0002_auto_20170328_0139'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_image', models.ImageField(upload_to='talent/extra_images')),
            ],
        ),
        migrations.CreateModel(
            name='GoriClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_title', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('HNB', '헬스 / 뷰티'), ('LAN', '외국어'), ('COM', '컴퓨터'), ('ART', '미술 / 음악'), ('SPO', '스포츠'), ('JOB', '전공 / 취업'), ('HOB', '이색취미')], max_length=3)),
                ('class_type', models.IntegerField(choices=[(0, '1:1'), (1, '그룹 수업'), (2, '원데이 수업')], default='1', max_length=1)),
                ('cover_image', models.ImageField(upload_to='talent/cover_image')),
                ('tutor_info', models.CharField(max_length=80)),
                ('class_info', models.CharField(max_length=150)),
                ('video1', models.URLField(blank=True)),
                ('video2', models.URLField(blank=True)),
                ('price_per_hour', models.IntegerField()),
                ('hours_per_class', models.IntegerField(max_length=2)),
                ('number_of_class', models.IntegerField(max_length=2)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.GoriClass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classimage',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.GoriClass'),
        ),
    ]
