# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 05:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0002_auto_20170328_0139'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='talent/extra_images')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('KN', '강남'), ('SC', '신촌'), ('SD', '사당'), ('JS', '잠실'), ('JR', '종로'), ('HH', '혜화'), ('YS', '용산'), ('HJ', '합정'), ('MD', '목동'), ('NW', '노원'), ('SDR', '신도림'), ('YDB', '영등포'), ('DDM', '동대문'), ('DG', '대구'), ('BS', '부산'), ('ONL', '온라인'), ('KOU', '고려대'), ('SNU', '서울대'), ('YOU', '연세대'), ('HOU', '홍익대'), ('EWWU', '이화여대'), ('BSU', '부산대'), ('JAU', '중앙대'), ('GGU', '건국대'), ('HYU', '한양대'), ('SCU', '서울시립대'), ('KHU', '경희대'), ('SJU', '세종대'), ('SGKU', '성균관대'), ('GWU', '광운대'), ('SMWU', '숙명여대'), ('SSWU', '성신여대'), ('KMU', '국민대'), ('SWU', '서울여대'), ('SGU', '서강대'), ('MJU', '명지대'), ('KIU', '한국외대'), ('SSU', '숭실대'), ('HYJ', '한예종'), ('DGU', '동국대'), ('STU', '서울과기대'), ('DSWU', '덕성여대'), ('SEU', '서울교대'), ('DDWU', '동덕여대')], max_length=4)),
                ('specific_location', models.CharField(choices=[('NEGO', '협의 후 결정'), ('SELF', '직접 입력')], help_text='상세 위치 정보', max_length=4)),
                ('location_info', models.CharField(help_text='직접 입력 10글자 내외', max_length=10)),
                ('extra_fee', models.CharField(choices=[('Y', '예, 있습니다'), ('N', '아니오, 없습니다')], default='N', help_text='장소 및 기타 비용이 있나요?', max_length=1)),
                ('day', models.CharField(choices=[('MO', '월'), ('TU', '화'), ('WE', '수'), ('TH', '목'), ('FR', '금'), ('SA', '토'), ('SU', '일')], max_length=2)),
                ('time', models.CharField(help_text=',로 나누어 입력해 주세요. 예시) 13-14시, 18-19시', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_title', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('HNB', '헬스 / 뷰티'), ('LAN', '외국어'), ('COM', '컴퓨터'), ('ART', '미술 / 음악'), ('SPO', '스포츠'), ('JOB', '전공 / 취업'), ('HOB', '이색취미')], max_length=3)),
                ('class_type', models.IntegerField(choices=[(0, '1:1'), (1, '그룹 수업'), (2, '원데이 수업')], default='1')),
                ('cover_image', models.ImageField(upload_to='talent/cover_image')),
                ('tutor_info', models.CharField(max_length=80)),
                ('class_info', models.CharField(max_length=150)),
                ('video1', models.URLField(blank=True)),
                ('video2', models.URLField(blank=True)),
                ('price_per_hour', models.IntegerField()),
                ('hours_per_class', models.IntegerField()),
                ('number_of_class', models.IntegerField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Tutor')),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.Talent'),
        ),
        migrations.AddField(
            model_name='location',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.Talent'),
        ),
        migrations.AddField(
            model_name='classimage',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.Talent'),
        ),
    ]
