# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='information',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='extra_fee_amount',
            field=models.CharField(blank=True, help_text='추가 비용: 예시) 재료 비용 1만원', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='time',
            field=models.CharField(help_text=',로 나누어 입력해 주세요. 예시) 13-14시, 18-19시', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='message_to_tutor',
            field=models.TextField(help_text='수강신청시 유저가 튜터에게 보내는 메세지'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='class_info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='talent',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='talent',
            name='tutor_info',
            field=models.TextField(),
        ),
    ]
