# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='wishlist_user',
        ),
    ]
