# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='max_number_student',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='min_number_student',
        ),
    ]
