# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goriclass',
            name='hours_per_class',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='goriclass',
            name='number_of_class',
            field=models.IntegerField(),
        ),
    ]
