# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='tutor_message',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
