# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registration',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='talent.Talent'),
        ),
    ]
