# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='is_verified',
            new_name='is_confirmed',
        ),
    ]
