# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='location_message',
            field=models.TextField(blank=True),
        ),
    ]
