# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='extra_fee_amount',
            field=models.CharField(default=1, help_text='추가 비용: 예시) 재료 비용 1만원', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='talent',
            name='hours_per_class',
            field=models.IntegerField(help_text='기본 수업 시간'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='number_of_class',
            field=models.IntegerField(help_text='한달 기준 총 수업 일'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='price_per_hour',
            field=models.IntegerField(help_text='시간당 가격'),
        ),
    ]
