# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 07:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('curriculum', models.IntegerField(default=1, help_text='5이하의 숫자를 입력하세요',
                                                   validators=[django.core.validators.MaxValueValidator(5),
                                                               django.core.validators.MinValueValidator(1)])),
                ('readiness', models.IntegerField(default=1, help_text='5이하의 숫자를 입력하세요',
                                                  validators=[django.core.validators.MaxValueValidator(5),
                                                              django.core.validators.MinValueValidator(1)])),
                ('timeliness', models.IntegerField(default=1, help_text='5이하의 숫자를 입력하세요',
                                                   validators=[django.core.validators.MaxValueValidator(5),
                                                               django.core.validators.MinValueValidator(1)])),
                ('delivery', models.IntegerField(default=1, help_text='5이하의 숫자를 입력하세요',
                                                 validators=[django.core.validators.MaxValueValidator(5),
                                                             django.core.validators.MinValueValidator(1)])),
                ('friendliness', models.IntegerField(default=1, help_text='5이하의 숫자를 입력하세요',
                                                     validators=[django.core.validators.MaxValueValidator(5),
                                                                 django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
