# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='talent',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='image',
            field=models.ImageField(blank=True, upload_to='talent/curriculum'),
        ),
    ]
