# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 08:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talent', '0002_auto_20170331_1558'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set([('talent', 'user')]),
        ),
    ]
