# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_talent_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='is_confirmed',
            new_name='is_verified',
        ),
    ]
