# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_auto_20170328_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='extra_fee_amount',
            field=models.CharField(blank=True, help_text='추가 비용: 예시) 재료 비용 1만원', max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_info',
            field=models.CharField(blank=True, help_text='직접 입력 10글자 내외', max_length=10),
        ),
    ]
