# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 07:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_auto_20170407_1643'),
    ]

    operations = [migrations.AddField(
            model_name='review',
            name='talent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='talent.Talent'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),

    ]
