# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_auto_20170404_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='registration',
        ),
    ]
