# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 13:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_auto_20170411_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 11, 22, 39, 56, 960907)),
        ),
    ]
