# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_auto_20170328_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talent',
            name='is_soldout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='talent',
            name='class_type',
            field=models.IntegerField(choices=[(0, '1:1'), (1, '그룹 수업'), (2, '원데이 수업')], default=1),
        ),
    ]
