# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_auto_20170411_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
