# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_auto_20170416_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='tutor_message',
            field=models.TextField(blank=True),
        ),
    ]
