# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 04:27
from __future__ import unicode_literals

import django.core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_auto_20170404_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.Talent'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
