# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='qna',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='talent.QnA'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qna',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='talent.QnA'),
        ),
    ]
