# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_auto_20170412_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='tutor',
        ),
    ]
