# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_remove_registration_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='talent.Talent'),
        ),
    ]
