# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0004_auto_20170411_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='qna',
        ),
        migrations.RemoveField(
            model_name='qna',
            name='talent',
        ),
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.RemoveField(
            model_name='question',
            name='qna',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='QnA',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
