# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 04:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='curriculum_rate',
            field=models.IntegerField(default=1, help_text='5이하의 숫자를 입력하세요', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='delivery',
            field=models.IntegerField(default=1, help_text='5이하의 숫자를 입력하세요', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='friendliness',
            field=models.IntegerField(default=1, help_text='5이하의 숫자를 입력하세요', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='readiness',
            field=models.IntegerField(default=1, help_text='5이하의 숫자를 입력하세요', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='timeliness',
            field=models.IntegerField(default=1, help_text='5이하의 숫자를 입력하세요', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
