# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0004_talent_location_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_message',
        ),
    ]
