# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('talent', '0004_remove_reply_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.Tutor'),
            preserve_default=False,
        ),
    ]
