# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0005_auto_20170401_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='delivery',
            new_name='delivery_rate',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='friendliness',
            new_name='friendliness_rate',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='readiness',
            new_name='readiness_rate',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='timeliness',
            new_name='timeliness_rate',
        ),
    ]
