# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0005_auto_20170404_0059'),
        ('talent', '0005_auto_20170405_0022'),
    ]

    operations = [
    ]
