# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0006_curriculum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'ordering': ['talent']},
        ),
    ]
