# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 10:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talent', '0008_auto_20170329_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='class_location',
            new_name='talent_location',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='talent',
        ),
        migrations.AddField(
            model_name='location',
            name='student',
            field=models.ManyToManyField(through='talent.Registration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration',
            name='experience_length',
            field=models.IntegerField(default=0, help_text='해당 수업관련 경력을 개월로 입력'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='message_to_tutor',
            field=models.CharField(help_text='수강신청시 유저가 튜터에게 보내는 메세지', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student_level',
            field=models.IntegerField(choices=[(1, '입문자'), (2, '초/중급자'), (3, '상급자')], help_text='레벨 선택'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='student',
            field=models.ManyToManyField(through='talent.WishList', to=settings.AUTH_USER_MODEL),
        ),
    ]
