# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0008_auto_20170401_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='class_type',
            field=models.IntegerField(choices=[(0, '1:1 수업'), (1, '그룹 수업'), (2, '원데이 수업')], default=1),
        ),
    ]
