# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0009_auto_20170329_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='student',
            new_name='registered_student',
        ),
        migrations.RenameField(
            model_name='talent',
            old_name='student',
            new_name='wishlist_user',
        ),
        migrations.AlterField(
            model_name='registration',
            name='message_to_tutor',
            field=models.CharField(blank=True, help_text='수강신청시 유저가 튜터에게 보내는 메세지', max_length=50),
        ),
    ]
