# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 07:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0009_auto_20170405_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='registration',
        ),
        migrations.AddField(
            model_name='review',
            name='talent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='talent.Talent'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration',
            name='talent_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.Location'),
        ),
    ]
