# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0010_auto_20170329_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='experience_length',
            field=models.IntegerField(blank=True, help_text='해당 수업관련 경력을 개월로 입력'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='message_to_tutor',
            field=models.CharField(help_text='수강신청시 유저가 튜터에게 보내는 메세지', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student_level',
            field=models.IntegerField(choices=[(1, '입문자'), (2, '초/중급자'), (3, '상급자')], default=1, help_text='레벨 선택'),
        ),
    ]
