# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0011_auto_20170405_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
